# Static HTML site - no build needed
[build]
  command = "echo 'No build needed for static HTML'"
  publish = "."

# Disable Next.js plugin
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=3600"

# Serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false